### ISSUE TITLE
Trying to install Calculix

### ISSUE THREAD

**Issue by khoitsma** [calculix/cae#11]
Using Conda, I tried several installation channels with no success -- I'm using Python 3.7.

conda install -c conda-forge calculix
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - calculix

Current channels:

  - https://conda.anaconda.org/conda-forge/win-32
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-32
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-32
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-32
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by oldninja** [comment]
Hi @khoitsma, why are you trying to install calculix from conda? I don't think there is a conda package for calculix. 
I think that all you need to do is download the latest version of the cae (binaries or source code) and have python3, unpack it and allow to be executed (give permissions).

**Comment by imirzov** [comment]
Sorry, @khoitsma , this repository isn't related to Conda. CAE is being developed without it.
If you need CalculiX - please, you can download it from [the official website](dhondt.de).
Also CalculiX is embed in [CAE](https://github.com/calculix/cae) - you can [download the latest release](https://github.com/calculix/cae/releases/tag/v0.8.0) and run with your Python 3.7. Here is info [how to run CAE](https://github.com/calculix/cae#how-to-use).
