### ISSUE TITLE
contact in the explicit solver

### ISSUE THREAD

**Issue by ywan459** [calculix/cae#12]
Hi there, thanks for supporting. 

I have recently assembled an model with the beam-to-solid contact. The explicit solver seems produce unreasonable results that the energy raised to the INF level at some stage. 

The load case is simple that
1. the cellular body (consisting many beam elements) sits on top of bottom supporting plate
2. the top loading plate moved downward to compress the cellular body. Top plate can only move in the vertical direction, and constraint by the imposed boundary conditions. 
3. the cellular has no other movement constraint, besides the contacts to the top and bottom plates.

I have attached zip files here, both the INP files and the results outputs. I do understand the the "beam" is not actual beam element, so the top and bottom plates were offset a bit (0.25mm) in order to accommodate the reproduced solids from the beams. The solver versions are 2.16 and 2.15.

I'd like to also confirm one thing, whether the "*tie " keywords were implemented for the explicit solver. I found it was not implemented. 

Thank you!

Regards
ywan459

[Contacts_Explicit.zip](https://github.com/calculix/cae/files/5048532/Contacts_Explicit.zip)

[Results_Cube_Tie_Explicit.zip](https://github.com/calculix/cae/files/5048537/Results_Cube_Tie_Explicit.zip)

**Comment by imirzov** [comment]
Dear ywan459,

Thanks for sharing your model. As I can see, beam-to-solid contact doesn't work. And I'm not sure if it should. Please, regarding CCX ask for support Mr. Guido Dhondt or CalculiX community:
https://calculix.discourse.group/
