### ISSUE TITLE
WARNING: *PLASTIC not known. Data ignored

### ISSUE THREAD

**Issue by CsatiZoltan** [calculix/cae#14]
Part of my input file is this:

```
*Material, name=Face_10
*Elastic
210000.0, 0.3
*Plastic
90.4500713201594, 0
```
I get a warning (`WARNING: *PLASTIC not known. Data ignored.`) but the material appears in the tree:

![elasto-plastic](https://user-images.githubusercontent.com/12742890/90402790-437ee400-e0a0-11ea-9836-06095dfd8aad.png)

Here is the complete log file: [1_elastoplastic_extended.log](https://github.com/calculix/cae/files/5084549/1_elastoplastic_extended.log)

**Comment by imirzov** [comment]
Thank you for sending the log! Those warnings come from CGX output. Just ignore them.

Another message from CGX is "ERROR in readfbd..." which means that there is no fbd-file you're trying to open.

My error in the log file is "ERROR: Can't parse elements", but I'll fix it soon.

**Comment by imirzov** [comment]
By the way, you have many sets and materials in the model. Is it opened fast? Please, could you publish your INP-file?

**Comment by CsatiZoltan** [comment]
Thanks for the rapid answer.
> Another message from CGX is "ERROR in readfbd..." which means that there is no fbd-file you're trying to open.

I didn't want to report two different errors in the same GitHub issue. What is an fbd file for?

> you have many sets and materials in the model. Is it opened fast?

Yes, I have a lot of element sets as different plasticity parameters are needed in those regions. It opened it a bit slowly, but waiting for a few seconds is not a problem for me.

> Please, could you publish your INP-file?

Here it is: [1_elastoplastic_extended.inp.txt](https://github.com/calculix/cae/files/5086667/1_elastoplastic_extended.inp.txt) (changed the file extension to .txt so that GitHub accepts it).

**Comment by imirzov** [comment]
Thank you for the INP file. It opens faster than I expected. So my INP parser is not so bad ))

FBD file consists of CGX commands, stores geometrical entities and defines a batch job using available commands. It's native format for CGX.
