### ISSUE TITLE
got an unexpected keyword argument 'blocks'

### ISSUE THREAD

**Issue by kmallick2000** [calculix/cae#16]
I followed instructions, installed all the requirements and tried to run CAE in Ubuntu 20.04. I am getting the following error:

Traceback (most recent call last):
  File "/home/kaushik/CalculiX/cae/src/cae.py", line 105, in <module>
    i.import_file(start_model)
  File "/home/kaushik/CalculiX/cae/src/importer.py", line 207, in import_file
    self.m.Mesh = model.parsers.mesh.Mesh(blocks=self.keyword_blocks)
TypeError: __init__() got an unexpected keyword argument 'blocks'

**Comment by imirzov** [comment]
Dear kmallick2000,

Looks like you're using latest sources which are under development.
Please, download sources from the latest release:
https://github.com/calculix/cae/archive/v0.8.0.zip
