### ISSUE TITLE
run cae.sh reminding of no module named ccx2paraview

### ISSUE THREAD

**Issue by solerzhuxy** [calculix/cae#18]
Hi, I mount the required software including ccx2paraview. The ccx2paraview was installed again by python3. The issue in the title was solved. But the case window disappeared suddenly after runing cae.sh.

  File "~/cae/src/cae.py", line 105, in <module>
    i.import_file(start_model)
  File "~/cae/src/importer.py", line 207, in import_file
    self.m.Mesh = model.parsers.mesh.Mesh(blocks=self.keyword_blocks)
TypeError: __init__() got an unexpected keyword argument 'blocks'

So how to solve it?

**Comment by imirzov** [comment]
https://github.com/calculix/cae/issues/19
