### ISSUE TITLE
Error Unexpected Keyword 'blocks'

### ISSUE THREAD

**Issue by mmanuel26** [calculix/cae#19]
Hi, I am running Linux, after following the installation instructions I tried to open an example. I always get the following error:
`~/Downloads/cae-master/src/importer.py", line 207, in import_file
    self.m.Mesh = model.parsers.mesh.Mesh(blocks=self.keyword_blocks)
TypeError: __init__() got an unexpected keyword argument 'blocks'`

What can I do?

**Comment by oldninja** [comment]
Could you share or check your input file? Particularly the part for the mesh...

**Comment by mmanuel26** [comment]
> Could you share or check your input file? Particularly the part for the mesh...

I am using the default.inp file

`*Heading
    Default_model_for_CalculiX_Advanced_Environment
**
** NODES
**
*Node
    1,          -3.,          -1.,           0.
    2,          -3.,          -1.,          -1.
    3,          -3.,          -1.,           1.
    4,          -3.,           0.,          -1.
    5,          -3.,           0.,           1.
    6,          -3.,           1.,          -1.
    7,          -3.,           1.,           0.
    8,          -3.,           1.,           1.
    9,          -2.,          -1.,          -2.
    10,          -2.,          -2.,          -1.
    11,          -2.,          -1.,           1.
    12,          -2.,          -2.,           1.
    13,          -1.,          -1.,          -3.
    14,          -2.,          -1.,          -1.
    15,          -2.,          -1.,           2.
    16,          -2.,           1.,          -2.
    17,          -2.,           1.,          -1.
    18,          -2.,           1.,           1.
    19,          -2.,           1.,           2.
    20,          -1.,           1.,           3.
    21,          -2.,           2.,          -1.
    22,          -2.,           2.,           1.
    23,          -1.,          -3.,          -1.
    24,          -1.,          -3.,           0.
    25,          -1.,          -3.,           1.
    26,          -1.,          -1.,          -2.
    27,          -1.,          -2.,          -2.
    28,          -1.,          -2.,          -1.
    29,          -1.,          -2.,           1.
    30,          -1.,          -2.,           2.
    31,          -1.,           0.,          -3.
    32,           0.,          -1.,          -3.
    33,          -1.,          -1.,          -1.
    34,          -1.,          -1.,           0.
    35,          -1.,           0.,          -1.
    36,          -1.,          -1.,           1.
    37,          -1.,           0.,           1.
    38,          -1.,          -1.,           2.
    39,          -1.,          -1.,           3.
    40,          -1.,           1.,          -3.
    41,          -1.,           1.,          -2.
    42,          -1.,           1.,          -1.
    43,          -1.,           1.,           0.
    44,          -1.,           1.,           1.
    45,          -1.,           0.,           3.
    46,          -1.,           1.,           2.
    47,           0.,           1.,           3.
    48,          -1.,           2.,          -1.
    49,          -1.,           3.,          -1.
    50,          -1.,           2.,          -2.
    51,          -1.,           3.,           0.
    52,          -1.,           2.,           1.
    53,          -1.,           3.,           1.
    54,          -1.,           2.,           2.
    55,           0.,          -3.,          -1.
    56,           1.,          -3.,          -1.
    57,           0.,          -3.,           1.
    58,           1.,          -2.,          -2.
    59,           1.,          -2.,          -1.
    60,           1.,          -1.,          -3.
    61,           1.,          -1.,          -2.
    62,           0.,          -1.,          -1.
    63,           1.,          -1.,          -1.
    64,           0.,          -1.,           1.
    65,           0.,          -1.,           3.
    66,           0.,           1.,          -3.
    67,           0.,           1.,          -1.
    68,           0.,           1.,           1.
    69,           1.,           1.,           1.
    70,           1.,           1.,           2.
    71,           1.,           1.,           3.
    72,           0.,           3.,          -1.
    73,           0.,           3.,           1.
    74,           1.,           3.,           1.
    75,           1.,           2.,           1.
    76,           1.,           2.,           2.
    77,           1.,          -3.,           0.
    78,           1.,          -3.,           1.
    79,           2.,          -2.,          -1.
    80,           1.,          -2.,           1.
    81,           1.,          -2.,           2.
    82,           1.,           0.,          -3.
    83,           2.,          -1.,          -2.
    84,           1.,          -1.,           0.
    85,           2.,          -1.,          -1.
    86,           1.,          -1.,           1.
    87,           1.,          -1.,           2.
    88,           1.,          -1.,           3.
    89,           1.,           1.,          -3.
    90,           1.,           1.,          -2.
    91,           1.,           0.,          -1.
    92,           1.,           0.,           1.
    93,           1.,           0.,           3.
    94,           1.,           1.,          -1.
    95,           1.,           1.,           0.
    96,           2.,           1.,           1.
    97,           2.,           1.,           2.
    98,           1.,           2.,          -2.
    99,           1.,           3.,          -1.
    100,           1.,           2.,          -1.
    101,           1.,           3.,           0.
    102,           2.,           2.,           1.
    103,           2.,          -2.,           1.
    104,           3.,          -1.,           0.
    105,           3.,          -1.,          -1.
    106,           3.,          -1.,           1.
    107,           2.,          -1.,           1.
    108,           2.,          -1.,           2.
    109,           2.,           1.,          -2.
    110,           3.,           0.,          -1.
    111,           3.,           0.,           1.
    112,           3.,           1.,          -1.
    113,           2.,           1.,          -1.
    114,           3.,           1.,           0.
    115,           3.,           1.,           1.
    116,           2.,           2.,          -1.
*Nset, nset=ALL_n, generate
    1, 116, 1
*Nset, nset=C3D4
    1,   2,   3,   4,   5,   6,   7,   8,  11,  13,  14,  17,  18,  20,  23,  24
    25,  26,  28,  29,  31,  32,  38,  39,  40,  41,  45,  46,  47,  48,  49,  51
    52,  53,  55,  56,  57,  59,  60,  61,  65,  66,  70,  71,  72,  73,  74,  75
    77,  78,  80,  82,  85,  87,  88,  89,  90,  93,  96,  99, 100, 101, 104, 105
    106, 107, 110, 111, 112, 113, 114, 115
*Nset, nset=C3D6
    1,   4,   5,   7,  11,  14,  17,  18,  24,  26,  28,  29,  31,  32,  33,  34
    35,  36,  37,  38,  41,  42,  43,  44,  45,  46,  47,  48,  51,  52,  55,  57
    59,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  72,  73,  75,  77,  80
    82,  84,  85,  86,  87,  90,  91,  92,  93,  94,  95,  96, 100, 101, 104, 107
    110, 111, 113, 114
*Nset, nset=C3D8
    1,   4,   5,   7,  24,  31,  32,  34,  35,  37,  43,  45,  47,  51,  55,  57
    62,  64,  65,  66,  67,  68,  72,  73,  77,  82,  84,  91,  92,  93,  95, 101
    104, 110, 111, 114
*Nset, nset=C3D10
    2,   3,   6,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20
    21,  22,  23,  25,  26,  27,  28,  29,  30,  33,  36,  38,  39,  40,  41,  42
    44,  46,  48,  49,  50,  52,  53,  54,  56,  58,  59,  60,  61,  63,  69,  70
    71,  74,  75,  76,  78,  79,  80,  81,  83,  85,  86,  87,  88,  89,  90,  94
    96,  97,  98,  99, 100, 102, 103, 105, 106, 107, 108, 109, 112, 113, 115, 116
*Nset, nset=C3D15, generate
    1,  116,    1
*Nset, nset=C3D20
    33, 34, 35, 36, 37, 42, 43, 44, 62, 63, 64, 67, 68, 69, 84, 86
    91, 92, 94, 95
**
** ELEMENTS
**
*Element, type=C3D4
    2, 73, 53, 51, 52
    10, 101,  74,  73,  75
    11,  72,  99, 101, 100
    12, 51, 49, 72, 48
    19, 65, 39, 45, 38
    20, 55, 23, 24, 28
    21, 66, 40, 31, 41
    31, 93, 88, 65, 87
    32, 77, 56, 55, 59
    33, 82, 89, 66, 90
    34, 45, 20, 47, 46
    35, 24, 25, 57, 29
    36, 31, 13, 32, 26
    43, 47, 71, 93, 70
    44, 57, 78, 77, 80
    45, 32, 60, 82, 61
    48,  7,  8,  5, 18
    52,  4,  6,  7, 17
    53,  5,  3,  1, 11
    55,  1,  2,  4, 14
    59, 110, 105, 104,  85
    60, 111, 115, 114,  96
    61, 114, 112, 110, 113
    64, 104, 106, 111, 107
*Element, type=C3D6
    6, 52, 51, 73, 44, 43, 68
    7, 75, 73, 101, 69, 68, 95
    8, 100, 101, 72, 94, 95, 67
    9, 48, 72, 51, 42, 67, 43
    25, 87, 65, 93, 86, 64, 92
    26, 59, 55, 77, 63, 62, 84
    27, 90, 66, 82, 94, 67, 91
    28, 46, 47, 45, 44, 68, 37
    29, 29, 57, 24, 36, 64, 34
    30, 26, 32, 31, 33, 62, 35
    37, 38, 45, 65, 36, 37, 64
    38, 28, 24, 55, 33, 34, 62
    39, 41, 31, 66, 42, 35, 67
    40, 70, 93, 47, 69, 92, 68
    41, 80, 77, 57, 86, 84, 64
    42, 61, 82, 32, 63, 91, 62
    50, 17, 7, 4, 42, 43, 35
    51, 11, 1, 5, 36, 34, 37
    54, 14, 4, 1, 33, 35, 34
    57, 85, 104, 110, 63, 84, 91
    58, 96, 114, 111, 69, 95, 92
    62, 113, 110, 114, 94, 91, 95
    63, 18, 5, 7, 44, 37, 43
    65, 107, 111, 104, 86, 92, 84
*Element, type=C3D8
    4, 51, 73, 68, 43, 72, 101, 95, 67
    22, 45, 65, 64, 37, 47, 93, 92, 68
    23, 24, 55, 62, 34, 57, 77, 84, 64
    24, 31, 66, 67, 35, 32, 82, 91, 62
    49, 5, 7, 43, 37, 1, 4, 35, 34
    56, 111, 104, 84, 92, 114, 110, 91, 95
*Element, type=C3D10
    5, 115, 74, 69, 71, 102, 75, 96, 97, 76, 70
    16, 89, 99, 94, 112, 98, 100, 90, 109, 116, 113
    17, 6, 49, 42, 40, 21, 48, 17, 16, 50, 41
    18, 20, 53, 44, 8, 54, 52, 46, 19, 22, 18
    72, 88, 78, 86, 106, 81, 80, 87, 108, 103, 107
    73, 3, 25, 36, 39, 12, 29, 11, 15, 30, 38
    74, 13, 23, 33, 2, 27, 28, 26, 9, 10, 14
    75, 105, 56, 63, 60, 79, 59, 85, 83, 58, 61
*Element, type=C3D15
    1, 99, 94, 112, 74, 69, 115, 100, 113, 116, 75, 96, 102, 101, 95, 114
    13, 49, 42, 40, 99, 94, 89, 48, 41, 50, 100, 90, 98, 72, 67, 66
    14, 53, 44, 8, 49, 42, 6, 52, 18, 22, 48, 17, 21, 51, 43, 7
    15, 74, 69, 71, 53, 44, 20, 75, 70, 76, 52, 46, 54, 73, 68, 47
    46, 56, 63, 60, 23, 33, 13, 59, 61, 58, 28, 26, 27, 55, 62, 32
    47, 25, 36, 39, 78, 86, 88, 29, 38, 30, 80, 87, 81, 57, 64, 65
    66, 71, 69, 115, 88, 86, 106, 70, 96, 97, 87, 107, 108, 93, 92, 111
    67, 78, 86, 106, 56, 63, 105, 80, 107, 103, 59, 85, 79, 77, 84, 104
    68, 60, 63, 105, 89, 94, 112, 61, 85, 83, 90, 113, 109, 82, 91, 110
    69, 39, 36, 3, 20, 44, 8, 38, 11, 15, 46, 18, 19, 45, 37, 5
    70, 23, 33, 2, 25, 36, 3, 28, 14, 10, 29, 11, 12, 24, 34, 1
    71, 40, 42, 6, 13, 33, 2, 41, 17, 16, 26, 14, 9, 31, 35, 4
*Element, type=C3D20
    3, 44, 36, 33, 42, 69, 86, 63, 94, 37, 34, 35, 43, 92, 84, 91,
    95, 68, 64, 62, 67
*Elset, elset=ALL_e, generate
    1, 75, 1
*Elset, elset=C3D4
    2, 10, 11, 12, 19, 20, 21, 31, 32, 33, 34, 35, 36, 43, 44, 45,
    48, 52, 53, 55, 59, 60, 61, 64
*Elset, elset=C3D6
    6, 7, 8, 9, 25, 26, 27, 28, 29, 30, 37, 38, 39, 40, 41, 42,
    50, 51, 54, 57, 58, 62, 63, 65
*Elset, elset=C3D8
    4, 22, 23, 24, 49, 56
*Elset, elset=C3D10
    5, 16, 17, 18, 72, 73, 74, 75
*Elset, elset=C3D15
    1, 13, 14, 15, 46, 47, 66, 67, 68, 69, 70, 71
*Elset, elset=C3D20
    3
**
** SURFACES
**
*Surface, type=ELEMENT, name=surf1
    C3D15, S5
*Surface, type=ELEMENT, name=surf2
    C3D8, S3
    C3D10, S2
    C3D20, S1
    C3D20, S2
    C3D20, S3
    C3D20, S4
    C3D20, S5
    C3D20, S6
*Surface, type=ELEMENT, name=surf3
    C3D4, S1
    C3D6, S2
**
** MATERIAL
**
*MATERIAL, NAME=default
    *DENSITY
        7800
    *ELASTIC, TYPE=ISO
        2e+11, 0.3
*SOLID SECTION, ELSET=ALL_e, MATERIAL=default
**
** STEP
**
*STEP, AMPLITUDE=RAMP
    *NO ANALYSIS
    *EL FILE, GLOBAL=YES, OUTPUT=3D
    *NODE FILE, GLOBAL=YES, OUTPUT=3D
    *BOUNDARY, OP=NEW
        ALL_n, 1, 6
    *END STEP
`

**Comment by imirzov** [comment]
Hi,

Here is release 0.8.0, source code, file importer.py, line 207:
    start_time = time.perf_counter()

Look like you're not using my release. So I need to ask, which installation instructions have you followed? Hope, those one: https://github.com/calculix/cae#how-to-use

**Comment by mmanuel26** [comment]
> Hi,
> 
> Here is release 0.8.0, source code, file importer.py, line 207:
> start_time = time.perf_counter()
> 
> Look like you're not using my release. So I need to ask, which installation instructions have you followed? Hope, those one: https://github.com/calculix/cae#how-to-use

Thank you, I was using the wrong source code. Thank you so much!

**Comment by imirzov** [comment]
Please, remember: latest source commit is a development version. It may contain bugs. Latest sources could be interesting for developers only. So, use releases page to get sources next time.

And, please, continue report any suspicious behaviour.
