### ISSUE TITLE
ERROR: Can't get 'CalculiX GraphiX' window.

### ISSUE THREAD

**Issue by mnekkach** [calculix/cae#20]
Hi,

I have launch cae.sh on RedHat 8.3 and I have this error message 

> ERROR: Can't get 'CalculiX GraphiX' window.

Can you help me to solve it.

**Comment by imirzov** [comment]
Hi,

Look here, line 157: https://github.com/calculix/cae/blob/master/src/gui/window.py
`if time.perf_counter() - start > 5:`

Keyword editor waits for CGX for 5 seconds, then emit error message. Try to increase wait time to 10 seconds (edit source file on your computer) and run application again. So line 157 in window.py file should be:
`if time.perf_counter() - start > 10:`

**Comment by mnekkach** [comment]
Thank for you answer, but I already tried to change the value of this line but I have the same error message.  

At the end of the log file I have this error about a libraries :

`/home/nekcorp/Downloads/cae-0.8.0/bin/cgx: error while loading shared libraries: libGLU.so.1: cannot open shared object file: No such file or directory`

**Comment by imirzov** [comment]
Looks like CGX simply can not start on RedHat. Try to install Mesa libGLU.
If so, this problem is not relevant to my CAE package.

**Comment by imirzov** [comment]
But thanks for the issue! Now I know that CGX may fail on some OS.
I'll implement some tests to inform users about missed libraries.

**Comment by mnekkach** [comment]
I tried to install mesa-libGlu on RedHat 8.3 and all it is right.
