### ISSUE TITLE
running on multicores

### ISSUE THREAD

**Issue by VivekVarkal** [calculix/cae#22]
Is it possible to run on multiple cores through cae? I couldn't find any?

**Comment by imirzov** [comment]
Sure, in CAE CalculiX runs automatically on all cores.

https://github.com/calculix/cae/blob/master/src/model/job.py
line 183:
os.environ['OMP_NUM_THREADS'] = str(os.cpu_count()) # enable multithreading

**Comment by VivekVarkal** [comment]
Yes, I got it. However, I am using for windows "CalculiX Advanced Environment v0.8.0" from "latest release". Can you please tell me where I could find the similar setting?

**Comment by imirzov** [comment]
In the same file, if you're using the source code version.
/src/model/job.py, line 171:
`os.environ['OMP_NUM_THREADS'] = str(os.cpu_count()) # enable multithreading`

Binary version has enabled multi-threading, and it can't be switched off.
