### ISSUE TITLE
FEM solver in detail (nodal force distribution)

### ISSUE THREAD

**Issue by hex41434** [calculix/cae#23]
Hi everyone! I am a little familiar with FEM and have recently simulated a simple model in freecad, in which a point force is applied on a metal part and I use calculix as solver. for a part of my research, I need to export a matrix from the FEM module, which might sound a bit strange to you!!

As far as I understood: in FEM we have: F=KD (Force Matrix, Stiffness and Displacement)
F is a matrix that represents Force for all nodes of the fem mesh. ( I think it is called nodal force distribution) this matrix should be calculated in the algorithm, and later, the K matrix will be made, to produce output D (displacement of nodes).

for some reason, I need the force vector which is applied on all nodes. (not the reaction force/ nor stress/ nor strain–> these are the outputs of FEM which I do not need!)

I thought F is made somewhere inside the code but unfortunately I could not find it inside the Freecad explicitly. I asked in FreeCAD Forum and they guided me to calculix developers.

so anyone can help me to find it? 

(I asked the same question in : 
https://calculix.discourse.group/t/nodal-force-distribution-matrix/675
but yet have not found the solution.)

thanks in advance

**Comment by imirzov** [comment]
There are no CalculiX developers here. Sorry.
Write to Mr. Guido Dhondt.
