### ISSUE TITLE
Add shell forces result computation capabilities

### ISSUE THREAD

**Issue by massimobrivio** [calculix/cae#27]
Hello. I was wondering if it would be possible to add membrane, bending and shear resultant elemental forces for shell elements S6 and S8R. Also for composite (multilayered) materials.

**Comment by imirzov** [comment]
Irrelevant. Sorry.

**Comment by massimobrivio** [comment]
may I ask why?

**Comment by imirzov** [comment]
Because this project does not modify CalculiX code. It only uses CalculiX.
Please, post feature requests regarding CCX and CGX to calculix.discourse.group

**Comment by massimobrivio** [comment]
My bad, sorry
