### ISSUE TITLE
Throws an error when executing cae.sh

### ISSUE THREAD

**Issue by dummifiedme** [calculix/cae#28]
I wished to used Calculix and installed cae, but it doesn't seem to be working 

![image](https://user-images.githubusercontent.com/68785729/183081510-1e1b59f8-7bc4-4b66-bfca-9e46da258e57.png)

**Comment by imirzov** [comment]
Thank you for posting the issue. But there are no messages from the application. You have some problems with fonts, not with my Python code. Do you have any additional error messages? Please, share them.
