### ISSUE TITLE
Configs are not saved

### ISSUE THREAD

**Issue by carlomontec** [calculix/cae#5]
I am running the latest release in Ubuntu 20.04, and the settings are not saved. When I restart the software is loaded back with defaults. 

I have no experience in Python, only MATLAB and Julia but I will try to have a look.

**Comment by imirzov** [comment]
Thank you for posting the issue. I've tested the code:
https://github.com/calculix/cae/blob/master/src/settings.py
It works fine. Please, check if file ./config/Settings_linux.env is created.

**Comment by imirzov** [comment]
Tested again. Can't see the problem. Please, post more precise bug description.
