### ISSUE TITLE
*include cards do not read relative paths.

### ISSUE THREAD

**Issue by carlomontec** [calculix/cae#6]
As far as I can tell the *include cards do not read relative paths. It tries to read the included decks at the same path of the main inp file. If I have a mesh in ./mesh/mesh.msh, it tries to read it from ./mesh.msh

**Comment by imirzov** [comment]
Fixed here:
https://github.com/calculix/cae/blob/master/src/file_tools.py
Thank you for the remark!

**Comment by imirzov** [comment]
CalculiX CAE v0.7
https://github.com/calculix/cae/releases/tag/v0.7
