### ISSUE TITLE
Sets with underscores are not plotted.

### ISSUE THREAD

**Issue by carlomontec** [calculix/cae#7]
If I click an NSET with name "Nn_root" is not plotted, giving the error 
`plot: set:Nn?root does not exist`

without the underscores works fine.

Btw, its a genius idea to interface to the CGX window!

**Comment by imirzov** [comment]
I've updated key codes, so they should be OK in the next CAE release. 
Please, test special symbols here: https://github.com/imirzov/sendkeys
Run text editor end send symbols: !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

**Comment by imirzov** [comment]
CalculiX CAE v0.7
https://github.com/calculix/cae/releases/tag/v0.7
